runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: pycrypto
  version: latest

handlers:
- url: /css
  static_dir: css
  secure: always

- url: /img
  static_dir: img
  secure: always

- url: /(.*\.js)
  mime_type: text/javascript
  static_files: static/\1
  upload: static/(.*\.js)

- url: /assets
  static_dir: assets
  expiration: "1h"
  http_headers:
    Vary: Accept-Encoding

- url: /.*
  script: main.application
  secure: always
